; example plugin entry
; plugin1 = Usb:\plugin\aplugin.xex
; Supported Paths: Usb (Mass0), Mass1, Mass2, Hdd, sfcx (16mb FlashFS)
;
[Plugins]
plugin1 =
plugin2 =
plugin3 =
plugin4 = 
plugin5 = 
